### ISSUE TITLE
error cryptopia_api

### ISSUE THREAD

**Issue by alicioromoli** [crypto-crew-tech/cryptopia-api-python#11]
Traceback (most recent call last):
  File "pump-dump.py", line 38, in <module>
    KEY, SECRET = get_secret("secrets.json")
  File "pump-dump.py", line 24, in get_secret
    secrets_json = json.load(secrets)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 2 column 5 (char 6)

**Comment by danton721** [comment]
On README.md:

> You have to create a secrets.json file with your public and secret key like this:
>
>{
>    "key" : "YOUR_PUBLIC_KEY",
>    "secret" : "YOUR_PRIVATE_KEY"
>}

Did you created this JSON file, respecting JSON format (double quotation marks, comma after public key, etc.)?

**Comment by saniales** [comment]
there was an error specified by your PR which has been solved, the correct format is
``` javascript
{
    "key" : "YOUR_PUBLIC_KEY",
    "secret" : "YOUR_PRIVATE_KEY"
}
```
