### ISSUE TITLE
Decoding error decode using "utf-8-sig"

### ISSUE THREAD

**Issue by danton721** [crypto-crew-tech/cryptopia-api-python#13]
Getting this error in decoding req...

python 3.6.4

```
Traceback (most recent call last):
  File "/Users/dantonheuer/PycharmProjects/project/exchange/pump_dump.py", line 46, in <module>
    BALANCE_BTC, ERROR = API.get_balance('BTC')
  File "/Users/dantonheuer/PycharmProjects/project/exchange/cryptopia_api.py", line 107, in get_balance
    post_parameters={'Currency': currency})
  File "/Users/dantonheuer/PycharmProjects/project/exchange/cryptopia_api.py", line 43, in api_query
    req = req.json()
  File "/Users/dantonheuer/PycharmProjects/project/venv/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 344, in loads
    s, 0)
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

**Comment by danton721** [comment]
Had kind of success using this on line 43 of API. 
`req = json.loads(req.content)`

But now the error is on response: "Signature does not match request parameters."

**Comment by danton721** [comment]
Fixed on my [last commit](https://github.com/crypto-crew-tech/cryptopia-api-python/pull/15/commits/333fd32de00e4389da60156ecbd1b3ce07bd11cd).
