### ISSUE TITLE
Cant start. Getting = Traceback (most recent call last):

### ISSUE THREAD

**Issue by Wrexen** [crypto-crew-tech/cryptopia-api-python#18]
Hello. Someone please can help me to get it to work ?
Getting this error when i execute it:

C:\Users\lars\Desktop\c>pump-dump.py
Traceback (most recent call last):
  File "C:\Users\lars\Desktop\c\pump-dump.py", line 45, in <module>
    BALANCE_BTC, ERROR = API.get_balance('BTC')
  File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 107, in get_balance
    post_parameters={'Currency': currency})
  File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 36, in api_query
    headers = self.secure_headers(url=url, post_data=post_data)
  File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 174, in secure_headers
    signature = self.key + "POST" + urlparse.quote(url).lower() + nonce + rcb64    # 'urlparse' on Py3 is actually urllib.parse imported as, so it is retrocompatible
AttributeError: 'function' object has no attribute 'quote'

Thanks

**Comment by kr0n0s1** [comment]
> Traceback (most recent call last):
File "C:\Users\lars\Desktop\c\pump-dump.py", line 45, in 
BALANCE_BTC, ERROR = API.get_balance('BTC')
File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 107, in get_balance
post_parameters={'Currency': currency})
File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 36, in api_query
headers = self.secure_headers(url=url, post_data=post_data)
File "C:\Users\lars\Desktop\c\cryptopia_api.py", line 174, in secure_headers
signature = self.key + "POST" + urlparse.quote(url).lower() + nonce + rcb64 # 'urlparse' on Py3 is actually urllib.parse imported as, so it is retrocompatible
AttributeError: 'function' object has no attribute 

I have this exact same issue.

**Comment by rodamaralgeo** [comment]
change your secret.json like this:

{
    "key" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "secret" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}

**Comment by danton721** [comment]
You are using python 2.7? Try changing `from urlparse import urlparse` to `import urllib as urlparse` and tell me if it works

**Comment by kr0n0s1** [comment]
> You are using python 2.7? On cryptopia_api.py file, try changing from urlparse import urlparse to import urllib as urlparse and tell me if it works

Thank you for the response. Yes I am using Python 2.7. With this change I am now getting this:

Traceback (most recent call last):
  File "pump-dump.py", line 45, in <module>
    BALANCE_BTC, ERROR = API.get_balance('BTC')
  File "C:\Python27\cryptopia_api.py", line 107, in get_balance
    post_parameters={'Currency': currency})
  File "C:\Python27\cryptopia_api.py", line 43, in api_query
    req = json.loads(req.content)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by saniales** [comment]
working on this, try to update, now it should work, paste here if you have other problem
