### ISSUE TITLE
Live Trading

### ISSUE THREAD

**Issue by mburakergenc** [crypto-crew-tech/cryptopia-api-python#5]
When running pump-dump.py in test mode it works just fine. However when running in live mode I get the following error. 

`Traceback (most recent call last):
  File "pump-dump.py", line 131, in <module>
    TRADE, ERROR = API.submit_trade(PUMP_COIN + '/BTC', 'Buy', ASK_BUY, NUM_COINS)
  File "/Users/akyayik/code/cryptopia-api-python/cryptopia_api.py", line 137, in submit_trade
    'Amount': amount})
  File "/Users/akyayik/code/cryptopia-api-python/cryptopia_api.py", line 42, in api_query
    if req['Message'] is None:
KeyError: 'Message'`

**Comment by mburakergenc** [comment]
I believe it should be
`if req['Error'] is None:
      error = "Unknown response error"
  else:
      error = req['Error']`

**Comment by saniales** [comment]
Probably Fixed by last commit
